name: Bug report
description: Submit a bug report
body:
  - type: markdown
    attributes:
      value: |
        **New to Python?**

        For help or advice on using Python, try one of the following options instead of opening a GitHub issue:
- type: textarea
  attributes:
    label: "What's wrong?"
