.TH backintime-config 1 "Aug 2024" "version 1.5.3-dev.3e80feee" "USER COMMANDS"
.SH NAME
config \- Back In Time configuration file.
.SH SYNOPSIS
~/.config/backintime/config
.br
/etc/backintime/config
.SH DESCRIPTION
Back In Time was developed as pure GUI program and so most functions are only usable with \fBbackintime-qt\fR. But it is possible to use Back In Time e.g. on a headless server. You have to create the configuration file (~/.config/backintime/config) manually. Look inside /usr/share/doc/backintime\-common/examples/ for examples.
.PP
The configuration file has the following format:
.br
keyword=arguments
.PP
Arguments don't need to be quoted. All characters are allowed except '='.
.PP
Run 'backintime check-config' to verify the configfile, create the snapshot folder and crontab entries.
.SH POSSIBLE KEYWORDS
.IP "\fIglobal.hash_collision\fR" 6
.RS
Type: int       Allowed Values: (0, 99999)
.br
Internal value used to prevent hash collisions on mountpoints. Do not change this.
.PP
Default: 0
.RE

.IP "\fIprofile<N>.snapshots.mode\fR" 6
.RS
Type: str       Allowed Values: local|local_encfs|ssh|ssh_encfs
.br
Use mode (or backend) for this snapshot. Look at 'man backintime' section 'Modes'.
.PP
Default: local
.RE

.SH SEE ALSO
.BR backintime (1),
.BR backintime-qt (1)
.PP
Back In Time also has a website: https://github.com/bit-team/backintime
.SH AUTHOR
This manual page was written by the Back In Time Team (<bit-dev@python.org>).
