.TH backintime-config 1 "Aug 2024" "version 1.5.3-dev.3e80feee" "USER COMMANDS"
.SH NAME
config \- Back In Time configuration file.
.SH SYNOPSIS
~/.config/backintime/config
.br
/etc/backintime/config
.SH DESCRIPTION
Back In Time was developed as pure GUI program and so most functions are only usable with \fBbackintime-qt\fR. But it is possible to use Back In Time e.g. on a headless server. You have to create the configuration file (~/.config/backintime/config) manually. Look inside /usr/share/doc/backintime\-common/examples/ for examples.
.PP
The configuration file has the following format:
.br
keyword=arguments
.PP
Arguments don't need to be quoted. All characters are allowed except '='.
.PP
Run 'backintime check-config' to verify the configfile, create the snapshot folder and crontab entries.
.SH POSSIBLE KEYWORDS
.IP "\fIglobal.hash_collision\fR" 6
.RS
Type: int       Allowed Values: 0-99999
.br
Internal value used to prevent hash collisions on mountpoints. Do not change this.
.PP
Default: 0
.RE

.IP "\fIglobal.language\fR" 6
.RS
Type: str       Allowed Values: ISO 639 language codes
.br
Language code (ISO 639) used to translate the user interface. If empty the operating systems current local is used. If 'en' the translation is not active and the original English source strings are used. It is the same if the value is unknown.
.PP

.RE

.IP "\fIglobal.use_flock\fR" 6
.RS
Type: bool      Allowed Values: true|false
.br
Prevent multiple snapshots (from different profiles or users) to be run at the same time.
.PP
Default: false
.RE

.IP "\fIsnapshots.ssh.path\fR" 6
.RS
Type: str       Allowed Values: absolute or relative path
.br
Snapshot path on remote host. If the path is relative (no leading '/') it will start from remote Users homedir. An empty path will be replaced with './'.
.PP

.RE

.IP "\fIsnapshots.ssh.host\fR" 6
.RS
Type: str       Allowed Values: IP or domain address
.br
Remote host used for mode 'ssh' and 'ssh_encfs'.
.PP

.RE

.IP "\fIsnapshots.ssh.port\fR" 6
.RS
Type: int       Allowed Values: 0-65535
.br
SSH Port on remote host.
.PP
Default: 22
.RE

.IP "\fIsnapshots.ssh.user\fR" 6
.RS
Type: str       Allowed Values: text
.br
Remote SSH user.
.BR backintime (1),
.BR backintime-qt (1)
.PP
Back In Time also has a website: https://github.com/bit-team/backintime
.SH AUTHOR
This manual page was written by the Back In Time Team (<bit-dev@python.org>).
